plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/corbandamukaitis/Desktop/Personal Projects/60minutesites.com/60minutesites-clean"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]